### ISSUE TITLE
Fail to build on Mac OS X 10.6

### ISSUE THREAD

**Issue by GoogleCodeExporter** [tinselcity/skipfish#12]
```
When building from tarball got following :

make all
cc skipfish.c -o skipfish -Wall -funsigned-char -g -ggdb -D_FORTIFY_SOURCE=0 
-O3 -Wno-format 
http_client.c database.c crawler.c analysis.c report.c -lcrypto -lssl -lidn -lz
http_client.c:38:18: error: idna.h: No such file or directory
http_client.c: In function ‘parse_url’:
http_client.c:275: warning: implicit declaration of function 
‘idna_to_ascii_8z’
http_client.c:275: error: ‘IDNA_SUCCESS’ undeclared (first use in this 
function)
http_client.c:275: error: (Each undeclared identifier is reported only once
http_client.c:275: error: for each function it appears in.)
report.c: In function ‘copy_static_code’:
report.c:744: warning: passing argument 3 of ‘scandir’ from incompatible 
pointer type
make: *** [skipfish] Error 1


Also, it looks like SVN for this project is mostly empty?

Andrei
```

Original issue reported on code.google.com by `andrei.t...@gmail.com` on 21 Mar 2010 at 3:56

**Comment by GoogleCodeExporter** [comment]
```
I just compiled this on my 10.6 system. You are missing the libidn library. If 
you have libidn installed via 
MacPorts rather than manually you will need to amend the Makefile from
CFLAGS_GEN = -Wall -funsigned-char -g -ggdb -D_FORTIFY_SOURCE=0 
to
CFLAGS_GEN = -Wall -funsigned-char -g -ggdb -D_FORTIFY_SOURCE=0 
-I/opt/local/include -L/opt/local/lib

The warning does not appear to affect basic function.
```

Original comment by `alexferr...@gmail.com` on 21 Mar 2010 at 4:06

**Comment by GoogleCodeExporter** [comment]
```
confirmed.  was able to build without any additional problems.  

I think that this kind of information should be added to "Known Issues" 
document.


```

Original comment by `andrei.t...@gmail.com` on 21 Mar 2010 at 4:41

**Comment by GoogleCodeExporter** [comment]
```
It is covered there (both installing libidn, and the -I bit).
```

Original comment by `lcam...@gmail.com` on 21 Mar 2010 at 4:56
- Changed state: **Duplicate**

**Comment by GoogleCodeExporter** [comment]
```
Does running this command generate any output?

find /usr/local -iname *idn*
```

Original comment by `alexferr...@gmail.com` on 22 Mar 2010 at 2:18

**Comment by GoogleCodeExporter** [comment]
```
find /usr/local -iname *idn*

produce nothing, but running 

find /opt/local -iname *idn*

produce lots of results.  I do not remember 100%, but I think /opt is where 
MacPorts installs by default.
```

Original comment by `andrei.t...@gmail.com` on 22 Mar 2010 at 1:22

**Comment by GoogleCodeExporter** [comment]
```
does "sudo port install libidn" say that it is installed?

If so try the modifications I posted above
```

Original comment by `alexferr...@gmail.com` on 22 Mar 2010 at 5:00

**Comment by GoogleCodeExporter** [comment]
```
@alexferrotm sorry, but I am not sure what are we trying to troubleshoot?  In 
my comment #2 I reported that I 
was able to build skipfish without any problems.
```

Original comment by `andrei.t...@gmail.com` on 22 Mar 2010 at 5:30

**Comment by GoogleCodeExporter** [comment]
```
oh, never mind, missed it was you saying that.
```

Original comment by `alexferr...@gmail.com` on 23 Mar 2010 at 1:11
